repos:
  - repo: local
    hooks:
      - id: migrations-check
        name: migrations-check
        entry: uv run python manage.py makemigrations --check
        language: system
        types: []
        pass_filenames: false

      - id: format
        name: format
        entry: uv run ruff format .
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: lint
        entry: uv run ruff check --fix .
        language: system
        types: [python]
        pass_filenames: false