[project]
name = "drf-template"
version = "1.0.0"
description = "A starter template for building REST APIs with DRF"
authors = []
readme = "README.md"
requires-python = ">=3.12,<4"
dependencies = [
    "django==6.0.3",
    "djangorestframework==3.17.1",
    "dj-database-url==3.1.2",
    "django-cors-headers==4.9.0",
    "django-environ==0.13.0",
    "drf-spectacular==0.29.0",
    "drf-standardized-errors==0.15.0",
    "django-structlog==10.0.0",
    "whitenoise==6.12.0",
    "httpx==0.28.1",
    "gevent==25.9.1",
    "gunicorn==25.1.0",
    "psycopg[binary]==3.3.3",
    "psycopg[pool]==3.3.3",
    "pytz==2026.1.post1",
    "rich==14.3.3",
]

[dependency-groups]
dev = [
    "django-stubs==6.0.1",
    "djangorestframework-stubs==3.16.8",
    "factory-boy>=3.3.3",
    "pre-commit==4.5.1",
    "pytest==9.0.2",
    "pytest-django==4.12.0",
    "pytest-recording>=0.13.4",
    "ruff==0.15.7",
]

[tool.uv]
exclude-newer = "7 days"

[tool.pytest.ini_options]
addopts = "--showlocals --no-migrations"
testpaths = ["tests"]
filterwarnings = [
    "ignore:datetime.datetime.utcnow*:DeprecationWarning",
]
DJANGO_SETTINGS_MODULE = "app.settings.testing"

[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
extend-select = ["I"] # enable import sorting
ignore = ["E266", "E501", "F403", "W291"]

[tool.django-stubs]
django_settings_module = "app.settings.local"
